package report

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

func newBuilder(t *testing.T) *Builder {
	t.Helper()
	b := New("Fleet brew baseline", "fleetctl audit brew")
	ts, err := time.Parse(time.RFC3339, "2026-05-16T16:17:23Z")
	if err != nil {
		t.Fatalf("setup ts: %v", err)
	}
	b.SetClock(func() time.Time { return ts })
	return b
}

func TestFileTimestamp_MatchesHermesShape(t *testing.T) {
	ts, _ := time.Parse(time.RFC3339, "2026-05-16T16:17:23Z")
	if got, want := FileTimestamp(ts), "20260516T161723Z"; got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestSlug(t *testing.T) {
	cases := []struct {
		in, want string
	}{
		{"Fleet brew baseline", "fleet-brew-baseline"},
		{"  Fleet Health  ", "fleet-health"},
		{"a/b/c", "a-b-c"},
		{"!!!", "report"},
		{"", "report"},
		{"Already-Slugged", "already-slugged"},
	}
	for _, c := range cases {
		if got := Slug(c.in); got != c.want {
			t.Errorf("Slug(%q) = %q, want %q", c.in, got, c.want)
		}
	}
}

func TestHeaderShape(t *testing.T) {
	b := newBuilder(t)
	out := b.String()
	wantHeader := "# Fleet brew baseline — 20260516T161723Z\n\n" +
		"> **Owned by Owera Software Ltda.** Generated by `fleetctl audit brew`. See [LICENSE](../../LICENSE).\n\n"
	if !strings.HasPrefix(out, wantHeader) {
		t.Errorf("header does not match expected shape.\ngot:\n%s\nwant prefix:\n%s", out, wantHeader)
	}
}

func TestMetaAndSection(t *testing.T) {
	b := newBuilder(t)
	b.Meta("Essentials", "`jq coreutils shellcheck gh wget ripgrep`")
	b.Meta("Mode", "`probe+install`")
	b.Section("State per host (after run)")
	out := b.String()
	for _, want := range []string{
		"- **Essentials**: `jq coreutils shellcheck gh wget ripgrep`",
		"- **Mode**: `probe+install`",
		"## State per host (after run)",
	} {
		if !strings.Contains(out, want) {
			t.Errorf("missing %q in:\n%s", want, out)
		}
	}
}

func TestTable_RendersGFM(t *testing.T) {
	b := newBuilder(t)
	b.Section("State per host (after run)")
	b.Table(
		[]string{"Host", "Arch", "Brew"},
		[][]string{
			{"gateway", "arm64", "/opt/homebrew/bin/brew"},
			{"hermes@claw1.local", "arm64", "/opt/homebrew/bin/brew"},
		},
	)
	out := b.String()
	for _, want := range []string{
		"| Host | Arch | Brew |",
		"|---|---|---|",
		"| gateway | arm64 | /opt/homebrew/bin/brew |",
		"| hermes@claw1.local | arm64 | /opt/homebrew/bin/brew |",
	} {
		if !strings.Contains(out, want) {
			t.Errorf("missing %q in:\n%s", want, out)
		}
	}
}

func TestTable_ShortRowsPadded(t *testing.T) {
	b := newBuilder(t)
	b.Table([]string{"A", "B", "C"}, [][]string{{"x"}})
	out := b.String()
	if !strings.Contains(out, "| x | - | - |") {
		t.Errorf("short row not padded with dashes:\n%s", out)
	}
}

func TestTable_PipeEscaped(t *testing.T) {
	b := newBuilder(t)
	b.Table([]string{"k"}, [][]string{{"a|b"}})
	out := b.String()
	if !strings.Contains(out, `| a\|b |`) {
		t.Errorf("pipe not escaped:\n%s", out)
	}
}

func TestCode(t *testing.T) {
	b := newBuilder(t)
	b.Code("bash", "echo hi\n")
	out := b.String()
	if !strings.Contains(out, "```bash\necho hi\n```") {
		t.Errorf("code block shape:\n%s", out)
	}
}

func TestNote(t *testing.T) {
	b := newBuilder(t)
	b.Note("first line\nsecond line")
	out := b.String()
	if !strings.Contains(out, "> first line\n> second line\n") {
		t.Errorf("note shape:\n%s", out)
	}
}

func TestBullet(t *testing.T) {
	b := newBuilder(t)
	b.Bullet("alpha")
	if !strings.Contains(b.String(), "- alpha\n") {
		t.Errorf("bullet not present")
	}
}

func TestHeading_ClampsLevel(t *testing.T) {
	b := newBuilder(t)
	b.Heading(0, "low")
	b.Heading(9, "high")
	out := b.String()
	if !strings.Contains(out, "\n# low\n") || !strings.Contains(out, "\n###### high\n") {
		t.Errorf("heading levels not clamped:\n%s", out)
	}
}

func TestSave_WritesFileWithSlugAndTimestamp(t *testing.T) {
	dir := t.TempDir()
	b := newBuilder(t)
	b.Section("Sec").Para("hi")
	path, err := b.Save(dir)
	if err != nil {
		t.Fatalf("Save: %v", err)
	}
	wantName := "fleet-brew-baseline-20260516T161723Z.md"
	if filepath.Base(path) != wantName {
		t.Errorf("path = %q, want basename %q", path, wantName)
	}
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("ReadFile: %v", err)
	}
	if !strings.HasPrefix(string(data), "# Fleet brew baseline — 20260516T161723Z") {
		t.Errorf("file content shape wrong:\n%s", data)
	}
	info, _ := os.Stat(path)
	if mode := info.Mode().Perm(); mode != 0o644 {
		t.Errorf("file mode = %o, want 0644", mode)
	}
}

func TestSave_CreatesParentDirs(t *testing.T) {
	dir := filepath.Join(t.TempDir(), "nested", "reports")
	b := newBuilder(t)
	if _, err := b.Save(dir); err != nil {
		t.Fatalf("Save: %v", err)
	}
	if _, err := os.Stat(dir); err != nil {
		t.Errorf("parent dir not created: %v", err)
	}
}

func TestSave_EmptyDir(t *testing.T) {
	b := newBuilder(t)
	if _, err := b.Save(""); err == nil {
		t.Fatal("expected error for empty dir")
	}
}

func TestTimestamp_StableAcrossCalls(t *testing.T) {
	b := newBuilder(t)
	first := b.String()
	second := b.String()
	if first != second {
		t.Errorf("rendering twice changed output:\n%s\nvs\n%s", first, second)
	}
}
