// Package report renders the markdown reports that owera-fleet commands
// drop into ~/.hermes/reports/. The output shape matches what hermes-setup
// scripts produced so existing tooling (operators reading reports in
// Obsidian, the eventual /document-release pipeline) keeps working.
//
// Canonical shape:
//
//	# <title> — <timestamp>
//
//	> **Owned by Owera Software Ltda.** Generated by `<command>`. ...
//
//	- **<meta-label>**: <value>
//	- ...
//
//	## <section>
//
//	<table | paragraph | code | note ...>
//
// A Builder is mutable and not safe for concurrent use — each command
// constructs one, fills it, then renders. The Save helper writes the
// rendered report with operator-readable permissions (0o644).
package report

import (
	"bytes"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"time"
)

// Builder accumulates a markdown report.
type Builder struct {
	title   string
	command string
	now     func() time.Time
	header  bytes.Buffer
	body    bytes.Buffer
	timestamp time.Time
}

// New returns a Builder with the canonical header pre-filled.
//
// command is the operator-facing invocation that produced the report
// (e.g., "fleetctl health" or "scripts/fleet-brew-baseline.sh"); it shows
// up in the attribution callout so future readers can reproduce the run.
func New(title, command string) *Builder {
	b := &Builder{
		title:   title,
		command: command,
		now:     func() time.Time { return time.Now().UTC() },
	}
	return b
}

// SetClock overrides the timestamp source. Intended for tests.
func (b *Builder) SetClock(now func() time.Time) { b.now = now }

// Timestamp returns the timestamp baked into the report header.
// It's set the first time Render/Bytes/Save runs; before that it's zero.
func (b *Builder) Timestamp() time.Time { return b.timestamp }

// Meta appends a "- **label**: value" line to the metadata bullet list
// at the top of the report. Multiple Meta calls preserve insertion order.
func (b *Builder) Meta(label, value string) *Builder {
	fmt.Fprintf(&b.body, "- **%s**: %s\n", label, value)
	return b
}

// Section starts a new "## <name>" section. Subsequent calls append to it.
func (b *Builder) Section(name string) *Builder {
	if b.body.Len() > 0 {
		b.body.WriteByte('\n')
	}
	fmt.Fprintf(&b.body, "## %s\n\n", name)
	return b
}

// Heading emits "<#×level> text". Level is clamped to [1, 6].
func (b *Builder) Heading(level int, text string) *Builder {
	if level < 1 {
		level = 1
	}
	if level > 6 {
		level = 6
	}
	fmt.Fprintf(&b.body, "%s %s\n\n", strings.Repeat("#", level), text)
	return b
}

// Para appends a paragraph.
func (b *Builder) Para(text string) *Builder {
	b.body.WriteString(text)
	b.body.WriteString("\n\n")
	return b
}

// Note appends a blockquote (typically used for callouts).
func (b *Builder) Note(text string) *Builder {
	for _, line := range strings.Split(strings.TrimRight(text, "\n"), "\n") {
		fmt.Fprintf(&b.body, "> %s\n", line)
	}
	b.body.WriteByte('\n')
	return b
}

// Bullet appends a single "- text" bullet line.
func (b *Builder) Bullet(text string) *Builder {
	fmt.Fprintf(&b.body, "- %s\n", text)
	return b
}

// Code appends a fenced code block. Pass "" for plain (no language tag).
func (b *Builder) Code(lang, body string) *Builder {
	fmt.Fprintf(&b.body, "```%s\n%s\n```\n\n", lang, strings.TrimRight(body, "\n"))
	return b
}

// Table appends a GitHub-flavored markdown table.
//
// Empty rows render as "-" in each cell so columns don't collapse. The
// header divider mirrors the column count even when headers contain "|".
func (b *Builder) Table(headers []string, rows [][]string) *Builder {
	if len(headers) == 0 {
		return b
	}
	esc := func(s string) string {
		s = strings.ReplaceAll(s, "|", `\|`)
		s = strings.ReplaceAll(s, "\n", " ")
		return s
	}
	b.body.WriteByte('|')
	for _, h := range headers {
		fmt.Fprintf(&b.body, " %s |", esc(h))
	}
	b.body.WriteByte('\n')
	b.body.WriteByte('|')
	for range headers {
		b.body.WriteString("---|")
	}
	b.body.WriteByte('\n')
	for _, row := range rows {
		b.body.WriteByte('|')
		for i := 0; i < len(headers); i++ {
			cell := "-"
			if i < len(row) && row[i] != "" {
				cell = esc(row[i])
			}
			fmt.Fprintf(&b.body, " %s |", cell)
		}
		b.body.WriteByte('\n')
	}
	b.body.WriteByte('\n')
	return b
}

// freezeHeader writes the title + attribution callout + a blank line
// separator into b.header. Called lazily by render so callers can keep
// mutating metadata up until they ask for output.
func (b *Builder) freezeHeader() {
	b.header.Reset()
	if b.timestamp.IsZero() {
		b.timestamp = b.now()
	}
	ts := FileTimestamp(b.timestamp)
	fmt.Fprintf(&b.header, "# %s — %s\n\n", b.title, ts)
	cmd := b.command
	if cmd == "" {
		cmd = "owera-fleet"
	}
	fmt.Fprintf(&b.header, "> **Owned by Owera Software Ltda.** Generated by `%s`. See [LICENSE](../../LICENSE).\n\n", cmd)
}

// Bytes returns the rendered markdown.
func (b *Builder) Bytes() []byte {
	b.freezeHeader()
	out := make([]byte, 0, b.header.Len()+b.body.Len())
	out = append(out, b.header.Bytes()...)
	out = append(out, b.body.Bytes()...)
	return out
}

// String is the string form of Bytes.
func (b *Builder) String() string { return string(b.Bytes()) }

// WriteTo writes the rendered report to w.
func (b *Builder) WriteTo(w io.Writer) (int64, error) {
	n, err := w.Write(b.Bytes())
	return int64(n), err
}

// Save writes the report under dir as "<slug>-<ts>.md" and returns the
// path. Parent directories are created. The file is mode 0o644 — reports
// are operator-readable diagnostics, never sensitive.
func (b *Builder) Save(dir string) (string, error) {
	if dir == "" {
		return "", fmt.Errorf("report: empty save dir")
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return "", fmt.Errorf("report: mkdir %s: %w", dir, err)
	}
	data := b.Bytes()
	path := filepath.Join(dir, Slug(b.title)+"-"+FileTimestamp(b.timestamp)+".md")
	if err := os.WriteFile(path, data, 0o644); err != nil {
		return "", fmt.Errorf("report: write %s: %w", path, err)
	}
	return path, nil
}

// FileTimestamp formats t as the compact "20260516T161723Z" form used by
// the existing reports/ filenames so chronological sort matches lexical sort.
func FileTimestamp(t time.Time) string {
	return t.UTC().Format("20060102T150405Z")
}

var slugSanitize = regexp.MustCompile(`[^a-z0-9]+`)

// Slug derives a filesystem-safe identifier from a title:
// lowercased, non-alphanumeric runs collapsed to "-".
func Slug(title string) string {
	s := strings.ToLower(strings.TrimSpace(title))
	s = slugSanitize.ReplaceAllString(s, "-")
	s = strings.Trim(s, "-")
	if s == "" {
		s = "report"
	}
	return s
}
