// gen_skills.go implements `fleetctl gen-skills` — renders one SKILL.md
// per registered subcommand into skills/<name>/SKILL.md.
//
// The on-disk skill files are the single source of truth for the agent
// runtime that loads them (Claude Code, the future Hermes skill index);
// the Go Skill() declarations are the authority for what they should
// contain. Drift between the two used to be a parallel-maintenance burden
// in hermes-setup. This command eliminates it: the renderer is
// deterministic and idempotent, so a CI `--check` run fails any PR that
// edits SKILL.md by hand without rerunning the generator.
package commands

import (
	"bytes"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"
)

var (
	genSkillsDir   string
	genSkillsCheck bool
)

var genSkillsCmd = &cobra.Command{
	Use:   "gen-skills",
	Short: "Render skills/<name>/SKILL.md from each subcommand's Skill() declaration",
	Long: `gen-skills walks the registered fleetctl subcommands, asks each one for
its Skill() metadata, and renders the corresponding skill manifest under
skills/<name>/SKILL.md.

By default it writes the manifests. With --check it instead compares the
on-disk content against what the generator would produce and exits 1 if
they differ — used in CI to keep SKILL.md in sync with Go source.`,
	Example: `  fleetctl gen-skills                     # regenerate skills/
  fleetctl gen-skills --check             # CI drift gate (no writes)
  fleetctl gen-skills --skills-dir /tmp/s # write to an alternate root`,
	RunE: runGenSkills,
}

func init() {
	genSkillsCmd.Flags().StringVar(&genSkillsDir, "skills-dir", "skills", "root directory for skill manifests")
	genSkillsCmd.Flags().BoolVar(&genSkillsCheck, "check", false, "compare on-disk to generated; exit 1 on drift (no writes)")
	rootCmd.AddCommand(genSkillsCmd)
}

func runGenSkills(cmd *cobra.Command, _ []string) error {
	skills := AllSkills()
	if len(skills) == 0 {
		return errors.New("gen-skills: no skills registered (every subcommand must call registerSkill in init)")
	}

	if genSkillsCheck {
		drift, err := checkSkills(genSkillsDir, skills)
		if err != nil {
			return err
		}
		if len(drift) > 0 {
			fmt.Fprintln(cmd.ErrOrStderr(), "gen-skills: drift detected:")
			for _, d := range drift {
				fmt.Fprintf(cmd.ErrOrStderr(), "  - %s\n", d)
			}
			return fmt.Errorf("gen-skills: %d skill manifest(s) out of sync; rerun 'fleetctl gen-skills'", len(drift))
		}
		fmt.Fprintf(cmd.OutOrStdout(), "gen-skills: %d skill(s) in sync\n", len(skills))
		return nil
	}

	for _, s := range skills {
		path := filepath.Join(genSkillsDir, s.Name, "SKILL.md")
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			return fmt.Errorf("gen-skills: mkdir %s: %w", filepath.Dir(path), err)
		}
		if err := os.WriteFile(path, RenderSkill(s), 0o644); err != nil {
			return fmt.Errorf("gen-skills: write %s: %w", path, err)
		}
	}
	fmt.Fprintf(cmd.OutOrStdout(), "gen-skills: wrote %d skill(s) under %s/\n", len(skills), genSkillsDir)
	return nil
}

// checkSkills returns a list of skill names whose on-disk content differs
// from the generated output (or is missing entirely).
func checkSkills(dir string, skills []Skill) ([]string, error) {
	var drift []string
	for _, s := range skills {
		path := filepath.Join(dir, s.Name, "SKILL.md")
		want := RenderSkill(s)
		got, err := os.ReadFile(path)
		if err != nil {
			if os.IsNotExist(err) {
				drift = append(drift, fmt.Sprintf("%s: missing (%s)", s.Name, path))
				continue
			}
			return nil, fmt.Errorf("gen-skills: read %s: %w", path, err)
		}
		if !bytes.Equal(got, want) {
			drift = append(drift, fmt.Sprintf("%s: content drift in %s", s.Name, path))
		}
	}
	return drift, nil
}

// RenderSkill produces the SKILL.md content for one skill. Deterministic:
// no timestamps, no hostnames, no environment leakage — so `--check`
// passes on a freshly-cloned repo regardless of who or when ran it.
//
// Exported so tests (and future tools that want to inline a manifest)
// can reuse the exact same rendering path the generator uses.
func RenderSkill(s Skill) []byte {
	var b bytes.Buffer
	fmt.Fprintln(&b, "---")
	fmt.Fprintf(&b, "name: owera-fleet/%s\n", s.Name)
	fmt.Fprintln(&b, "category: owera-fleet")
	fmt.Fprintln(&b, "version: 1.0.0")
	fmt.Fprintln(&b, "source: generated by `fleetctl gen-skills`; edit cmd/fleetctl/commands/*.go and rerun")
	fmt.Fprintln(&b, "---")
	fmt.Fprintln(&b)
	fmt.Fprintf(&b, "# %s\n", s.Name)
	fmt.Fprintln(&b)
	if s.Trigger != "" {
		fmt.Fprintf(&b, "**Trigger:** `%s`\n\n", s.Trigger)
	}
	if s.Summary != "" {
		fmt.Fprintln(&b, "## Summary")
		fmt.Fprintln(&b)
		fmt.Fprintln(&b, strings.TrimSpace(s.Summary))
		fmt.Fprintln(&b)
	}
	if len(s.Args) > 0 {
		fmt.Fprintln(&b, "## Arguments")
		fmt.Fprintln(&b)
		fmt.Fprintln(&b, "| Flag | Meaning |")
		fmt.Fprintln(&b, "|---|---|")
		for _, a := range s.Args {
			fmt.Fprintf(&b, "| `%s` | %s |\n", a.Name, escapeTableCell(a.Description))
		}
		fmt.Fprintln(&b)
	}
	if len(s.Examples) > 0 {
		fmt.Fprintln(&b, "## Examples")
		fmt.Fprintln(&b)
		for _, e := range s.Examples {
			fmt.Fprintf(&b, "**%s:**\n", e.Description)
			fmt.Fprintln(&b)
			fmt.Fprintln(&b, "```")
			fmt.Fprintln(&b, e.Command)
			fmt.Fprintln(&b, "```")
			fmt.Fprintln(&b)
		}
	}
	return b.Bytes()
}

func escapeTableCell(s string) string {
	s = strings.ReplaceAll(s, "|", `\|`)
	s = strings.ReplaceAll(s, "\n", " ")
	return s
}

func genSkillsSkill() Skill {
	return Skill{
		Name:    "gen-skills",
		Trigger: "/gen-skills",
		Summary: "Render skills/<name>/SKILL.md from every fleetctl subcommand's Skill() declaration.",
		Args: []SkillArg{
			{Name: "--skills-dir DIR", Description: "Override output root (default: skills/)."},
			{Name: "--check", Description: "Compare on-disk to generated; exit 1 on drift (no writes). Used by CI."},
		},
		Examples: []SkillExample{
			{Description: "Regenerate all skills", Command: "fleetctl gen-skills"},
			{Description: "CI drift gate", Command: "fleetctl gen-skills --check"},
		},
	}
}

func init() { registerSkill("gen-skills", genSkillsSkill) }
